name: Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@main
        with:
          node-version: '14.x'
          
      - name: Install dependencies
        run: yarn
      
      - name: Run linting
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@main
        with:
          node-version: '14.x'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '4.2'
          
      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
        env:
          REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
